apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightreign
  namespace: staging # or production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nightreign
  template:
    metadata:
      labels:
        app: nightreign
    spec:
      containers:
      - name: nightreign
        image: jacktham/nightreign:staging  # 依環境變動
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nightreign-service
  namespace: staging # or production
spec:
  selector:
    app: nightreign
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
