name: CI Build and Push

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jack.tham@kkday.com
        password: Kit_960611565181

    - name: Build Docker image
      run: docker build -t jacktham/frontend:${{ github.ref_name }} .

    - name: Push Docker image
      run: docker push jacktham/frontend:${{ github.ref_name }}
